### ISSUE TITLE
The high-bitrate web radio is not working

### ISSUE THREAD

**Issue by 2serg2** [CelliesProjects/ESP32_VS1053_Stream#15]
If the stream speed is 196 kbit/s or higher, the ESP32 goes into 'sleep' mode after receiving a certain amount of bytes. At my home, the Internet speed is 10 Mbit/s, and the sound gets interrupted. If a higher Internet speed is used, some radio stations start playing normally.
Example code:
`WiFi.begin(SSID, PSK);`
You need to insert the function:
`WiFi.setSleep(false);`
For example, try these stations:
http://listen1.myradio24.com:9000/5967
https://stream.realhardstyle.nl/320
http://89.223.45.5:8000/progressive-160
http://streamer.radiovseti.ru:8000/320
http://icecast.err.ee/klarajazzkorge.mp3
http://audio.bfmtv.com/bfmradio_128.mp3

**Comment by CelliesProjects** [comment]
Yes, you are right. A common problem with the esp32 wifi. I forgot it in the examples.
Thanks for mentioning.
