### ISSUE TITLE
I am using this library to listen to my favorite radios, from time to time (about 30-60min) the Esp32 reboots and then keeps rebooting for a few minutes immediately after the first sounds from the station comes out, then it functions normally again. Any ideas?

### ISSUE THREAD

**Issue by lidense** [CelliesProjects/ESP32_VS1053_Stream#18]

**Comment by CelliesProjects** [comment]
Not really. Sounds like a failing or too hot 3.3v LDO.

**Comment by lidense** [comment]
OK thanks.

**Comment by lidense** [comment]
But if I disable PSRAM I will not have the ringbuffer? 
..that will increase the risk of having clicks during streaming? 
Why is a ringbuffer only implemented if PSRAM is present? Isn't it possible to implement it in RAM using one of the 2 cores of the esp32?

**Comment by CelliesProjects** [comment]
> But if I disable PSRAM I will not have the ringbuffer?

No ringbuffer without PSRAM. Normal RAM is too small for a second buffer. 

> ..that will increase the risk of having clicks during streaming?

Yes, as the vs1053 is filled straight from the http buffer which has to fit in normal RAM.

> Why is a ringbuffer only implemented if PSRAM is present? Isn't it possible to implement it in RAM using one of the 2 cores of the esp32?

Basically the same answer as the first question. Normal RAM is too small for a second buffer.

But it is up to you. You can use a PSRAM buffer if you want. 
I just do not do it myself -on pre S2 and S3 boards- and do not recommend doing it.
None of my pre S2 and S3 boards run stable when PSRAM is used. They reboot within a couple of days. Sometimes within minutes.

ESP32-S2 and S3 boards -with a good LDO etc- run for weeks on end with PSRAM used.

**Comment by lidense** [comment]
Thanks. I have an  Adafruit_feather_esp32s3_tft with an Adafruit Music Maker FeatherWing , I like it because the esp32 and vs1053 are mounted one on top of the other with no wires (I had a lot of interference/instability when using a vs1053 board connected to the esp32 with Dupont wires).
Do you think my setup has  good enough PSRAM? If not which esp32 board/vs1053 would you recommend?

**Comment by CelliesProjects** [comment]
That is a very nice combo. If Adafruit might ever stock up again on the featherwing boards I will get some myself. 

On S2 and S3 boards the psram issues are fixed, so with your S3 board you should have no psram issues.

**Comment by CelliesProjects** [comment]
To go back to your original question: I got no idea.

**Comment by CelliesProjects** [comment]
And maybe you could run the following code to actually see what hardware revision you have.

```c++
#include <Arduino.h>
#include <esp_chip_info.h>

void setup() {
#if defined(CONFIG_IDF_TARGET_ESP32S2) && ARDUHAL_LOG_LEVEL != ARDUHAL_LOG_LEVEL_NONE
    delay(3000);
    Serial.setDebugOutput(true);
#endif
    Serial.begin(115200);

    /* Print chip information */
    esp_chip_info_t chip_info;
    esp_chip_info(&chip_info);
    Serial.printf("This is ESP32 chip with %d CPU cores, WiFi%s%s\n",
            chip_info.cores,
            (chip_info.features & CHIP_FEATURE_BT) ? "/BT" : "",
            (chip_info.features & CHIP_FEATURE_BLE) ? "/BLE" : "");

    Serial.printf("silicon revision %d\n", chip_info.revision);

    Serial.printf("%dMB %s flash\n", spi_flash_get_chip_size() / (1024 * 1024),
            (chip_info.features & CHIP_FEATURE_EMB_FLASH) ? "embedded" : "external");
}

void loop() {
}
```

**Comment by lidense** [comment]
OK thanks


----- Mail original -----
De: "Cellie" ***@***.***>
À: "CelliesProjects/ESP32_VS1053_Stream" ***@***.***>
Cc: "lidense" ***@***.***>, "Author" ***@***.***>
Envoyé: Mercredi 4 Octobre 2023 09:59:13
Objet: Re: [CelliesProjects/ESP32_VS1053_Stream] I am using this library to listen to my favorite radios, from time to time (about 30-60min) the Esp32 reboots and then keeps rebooting for a few minutes immediately after the first sounds from the station comes out, then it functions normally again. Any ideas? (Issue #18)





That is a very nice combo. If Adafruit might ever stock up again on the featherwing boards I will get some myself. 

On S2 and S3 boards the psram issues are fixed, so with your S3 board you should have no psram issues.

**Comment by CelliesProjects** [comment]
For the rebooting problem I think I found the solution.

https://github.com/CelliesProjects/ESP32_VS1053_Stream#prevent-reboots-while-playing

Let me know if it works for you.

**Comment by lidense** [comment]
I have revision V3, so I put "-D BOARD_HAS_PSRAM" in platformio.ini and it seems to work OK.
Do you have any idea concerning the HLS question above (2 days ago)?
Thanks and regards
