### ISSUE TITLE
lot of compilation errors with arduino Arduino ESP32 pre-release version 3.0.0-aplha 3 

### ISSUE THREAD

**Issue by fbell58** [CelliesProjects/ESP32_VS1053_Stream#26]
Hello i use version
The Arduino ESP32 pre-release version 3.0.0-aplha 3 is based on the ESP-IDF v5.1 ([release notes](https://github.com/espressif/esp-idf/releases/tag/v5.1)) and is major release supporting new version of ESP-IDF 5.1. This release introduce breaking changes and support for new SoCs, ESP32-H2 and ESP32-C6.

beecause i need to use a ESP32-C6 device and I get many errors with le library. I have try with an ESP32 wroom same errors ......
[error.log](https://github.com/CelliesProjects/ESP32_VS1053_Stream/files/14896052/error.log)

ci attached above log

**Comment by CelliesProjects** [comment]
This issue should be fixed by #39
