### ISSUE TITLE
WifiClient not declared

### ISSUE THREAD

**Issue by Sikkens99** [CelliesProjects/ESP32_VS1053_Stream#34]
Since two days I suddenly get this error compiling a program that worked before without problems:
"....libraries\ESP32_VS1053_Stream\src/ESP32_VS1053_Stream.h:78:27: error: 'WiFiClient' has not been declared"
I appreciate your ideas what could be the problem here.

Marten Sikkens

**Comment by Sikkens99** [comment]
...and the above-mentioned compilation message is then follwed by "exit status 1".

**Comment by CelliesProjects** [comment]
> Since two days I suddenly get this error compiling a program that worked before without problems:

Those are the best errors.

I was toying around with the 3.0.1 esp32 update and there I also got problems with WifiClient not being defined.
Maybe your IDE updated to 3.0.1 without telling you so?

**Comment by Sikkens99** [comment]
Indeed I updated the ESP32 IDE to version 3.0.1 without realizing that this could give problems.  I went back to version 2.0.17 and that indeed solved the WiFiClient Not Declared error! Thanks for letiing me know that this could be the problem!
